config/routes.rb
Rails.application.routes.draw do
  root 'archives#index', defaults: { category: 'nonadult' }
  resources :archives, only: [:index, :show], param: :uuid

  get '/guidline',  to: 'static_pages#guidline', as: :guidline

  get 'pickups',           to: 'archives#pickups', as: :pickups
  get 'pickups/:category', to: 'archives#pickups', as: :pickups_category

  get 'sites/:site', to: 'archives#index', as: :site
  get '(:category)',   to: 'archives#index', as: :category, defaults: { category: 'nonadult' }

  get 'rss/:category.:format', to: 'feeds#show', as: :rss, defaults: { format: 'xml' } 

  resource :registration, only: [:new, :create]
  resource :contact, only: [:new, :create]

  namespace :admin do
    resources :sites
    resources :batches
  end
end

app/views/layouts/admin/_header.html.haml
#header
  .logo_title
    MobMin

%ul
  %li
    = link_to 'サイト一覧', admin_sites_path
  %li
    = link_to '新規登録', new_admin_site_path

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %title AdminlteRails51Sample
    = csrf_meta_tags
    %meta{ charset: 'utf-8' }
    %meta{ http:{ :equiv =>"X-UA-Compatible"}, content: 'IE=edge' }
    %meta{ content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no', name: 'viewport' }
    = stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload'
    %link{ rel: 'stylesheet', href: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css' }
    %link{ rel: 'stylesheet', href: 'https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css' }
  %body{ class: 'hold-transition skin-blue sidebar-mini' }
    .wrapper
      %header.main-header
        = link_to 'MobMin', '#', class: 'logo'

      %aside.main-sidebar
        %section.sidebar
          %ul.sidebar-menu.tree
            %li
              = link_to admin_sites_path do
                %i.fa.fa-list
                サイト管理
            %li
              = link_to admin_batches_path do
                %i.fa.fa-rss
                バッチ管理

      .content-wrapper
        = yield