config/routes.rb
Rails.application.routes.draw do
  root 'archives#index', defaults: { category: 'nonadult' }
  resources :archives, only: [:index, :show], param: :uuid

  get '/guidline',  to: 'static_pages#guidline', as: :guidline

  get 'pickups',           to: 'archives#pickups', as: :pickups
  get 'pickups/:category', to: 'archives#pickups', as: :pickups_category

  get 'sites/:site', to: 'archives#index', as: :site
  get '(:category)',   to: 'archives#index', as: :category, defaults: { category: 'nonadult' }

  get 'rss/:category.:format', to: 'feeds#show', as: :rss, defaults: { format: 'xml' } 

  resource :registration, only: [:new, :create]
  resource :contact, only: [:new, :create]

  namespace :admin do
    resources :sites
    resources :batches
  end
end

app/controllers/admin/batches_controller.rb
class Admin::BatchesController < Admin::ApplicationController
  before_action :set_site, only: [:edit, :update, :destroy]
  before_action :set_sites, only: [:index]

  def index
  end

  def new
    @site = Site.new
  end

  def edit
  end

  def update
    @site.update_attributes!(site_params)
    redirect_to edit_admin_site_path(@site), notice: 'サイトを更新しました'
  rescue
    error_message = @site.errors.full_messages
    flash.now[:alert] = "サイトの更新に失敗しました。#{error_message}"
    render :edit
  end

  def create
    @site = Site.new(site_params)
    @site.save!
    redirect_to admin_sites_path, notice: 'サイトを登録しました'
  rescue
    error_message = @site.errors.full_messages
    flash.now[:alert] = "サイトの登録に失敗しました。#{error_message}"
    render :new
  end

  def destroy
    @site.destroy!
    redirect_to admin_sites_path, notice: 'サイトを削除しました'
  rescue
    error_message = @site.errors.full_messages
    flash.now[:alert] = "サイトの削除に失敗しました。#{error_message}"
    render :edit
  end

  private

  def set_site
    @site = Site.find(params[:id])
  end

  def set_sites
    @sites = Site.page(params[:page]).active
  end

  def site_params
    params.require(:site).permit(:name, :url, :rss_url, :email, :description, :category_code)
  end
end

app/views/admin/batches/_batch.html.haml
%tr
  %td= batch.id
  %td= batch.name
  %td= batch.command
  %td
    = link_to '表示', edit_admin_batch_path(batch), { class: 'btn btn-primary btn-sm btn-block' }
    = link_to '実行', exec_admin_batch_path(batch), { class: 'btn btn-primary btn-sm btn-block' }

app/views/admin/batches/_form.html.haml
.box
  .box-header.with-border
    %h3.box-title
      - if batch.persisted?
        編集: ##{batch.id}
      - else
        新規作成

  - url = batch.persisted? ? admin_batch_path(batch) : admin_batch_path
  = form_for(batch, url: url, html: { class: 'form-horizontal', role: 'form' }) do |f|
    .box-body
      .form-group
        %label.col-md-2.control-label{ for: 'name' } バッチ名
        .col-sm-10
          = f.text_field :name, placeholder: '', class: 'form-control'

      .form-group
        %label.col-md-2.control-label{ for: 'command' } コマンド
        .col-sm-10
          = f.text_area :command, placeholder: '', class: 'form-control'

    .box-footer
      .row
        .col-md-offset-2.col-md-10
          =button_tag class: 'btn btn-info' do
            %i.ace-icon.fa.fa-check.bigger-110
            保存

          - if site.persisted?
            = link_to admin_site_path, class: 'btn btn-danger delete_button',
              method: :delete, data: { confirm: '削除してもよろしいですか？' } do
              %i.ace-icon.fa.fa-trash-o.bigger-110
              削除

app/views/admin/batches/edit.html.haml
%section.content-header
  %h1 バッチ管理
  %ol.breadcrumb
    %li
      = link_to admin_batches_path do
        バッチ管理
    %li.active
      編集

%section.content
  = bootstrap_flash
  = render 'form', site: @batch

app/views/admin/batches/index.html.haml
%section.content-header
  %h1 バッチ管理
    
  %ol.breadcrumb
    %li.active
      バッチ管理

%section.content
  = bootstrap_flash
  .box
    .box-header
      = link_to new_admin_batch_path, { class: 'btn btn-primary' } do
        %i.fa.fa-plus
        新規作成

    .box-body.table-responsive
      = page_entries_info @batches

      %table.table.table-bordered
        %thead
          %tr
            %th #
            %th バッチ名
            %th コマンド
            %th 操作
        %tbody
          = render @batches

    = paginate @batches

app/views/admin/batches/new.html.haml
%section.content-header
  %h1 サイト
  %ol.breadcrumb
    %li
      = link_to admin_sites_path do
        サイト
    %li.active
      新規作成

%section.content
  = bootstrap_flash
  = render 'form', site: @site