config/routes.rb
Rails.application.routes.draw do
  root 'archives#index', defaults: { category: 'nonadult' }
  resources :archives, only: [:index, :show], param: :uuid

  get '/guidline',  to: 'static_pages#guidline', as: :guidline

  get 'pickups',           to: 'archives#pickups', as: :pickups
  get 'pickups/:category', to: 'archives#pickups', as: :pickups_category

  get 'sites/:site', to: 'archives#index', as: :site
  get '(:category)',   to: 'archives#index', as: :category, defaults: { category: 'nonadult' }

  get 'rss/:category.:format', to: 'feeds#show', as: :rss, defaults: { format: 'xml' } 

  resource :registration, only: [:new, :create]
  resource :contact, only: [:new, :create]

  namespace :admin do
    resources :sites
    resources :batches
  end
end

app/views/layouts/_breadcrumb.html.haml
.breadcrumb
  .breadcrumb_inner
    %ul
      %li
        = link_to root_path do
          %span もぶアンテナトップ
      - breadcrumb.each do |title, url|
        %li
          = link_to url do
            %span #{title}

app/views/layouts/_footer.html.haml
#footer
  .container
    .footer_inner
      .row
        .col-3
          .logo
            %h1
              .icon= raw logo_svg(color: '#333', width: '35px', height: '35px')
        .col-9
          .footer_nav
            = link_to 'ブログ運営者向け', guidline_path
            |
            = link_to 'お問い合わせ', contact_path
            .copyright
              Copyright もぶアンテナ All Right Reserved.

app/views/layouts/_header.html.haml
#header
  .container

app/views/layouts/_sidebar.html.haml
.sidebar
  .column
    .ranking_title
      ランキング総合
    .ranking_lead
      最近人気のあった記事
      .pickups
        - Archive.pickups.each do |archive|
          .pickup
            .pickup_thumb
              = image_tag archive.image.url(:thumb) if archive.image.present?
            .pickup_title
              = archive.title

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ charset: 'utf-8' }
    %meta{ 'http-equiv' => 'x-ua-compatible', 'content' => 'IE=edge' }
    = title_and_meta_tags
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = raw yield :css
    = javascript_include_tag 'application'

  %body{ class: "#{absolute_css_class_name}", id: 'pc_page' }
    #header_wrapper
      #header_wrapper_inner
        = render 'layouts/header'

    %nav.nav
      %ul.nav_categories
        %li.icon= raw logo_svg(color: '#242424', width: '30px', height: '30px')
        - current = params[:category] || '2ch'
        - categories.each do |category|
          %li.nav_category{ class: current == category ? "current #{category}" : category }
            = link_to t("categories.#{category}"), category_path(category)

    %main
      = content_for(:content_main) ? yield(:content_main) : yield

    #footer_wrapper
      #footer_wrapper_inner
        = render 'layouts/footer'

app/views/layouts/archives.html.haml
- content_for(:content_main) do
  = yield

= render template: 'layouts/application'

app/views/layouts/static_pages.html.haml
- content_for(:content_main) do
  = yield

= render template: 'layouts/application'